name: CI
on:
  push:
    branches: [ "main" ]
jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

name: CI/CD Pipeline
+on: [push]
+# env:
+#   IMAGE_NAME: nanajanashia/demo-app
+#   IMAGE_TAG: python-app-1.0
+
jobs:
+  test:
+    name: Run Tests
+    runs-on: ubuntu-latest
+    # container:
+    #   image: python:3.9-slim-buster
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4.2.2
+
+      - name: Set up Python
+        uses: actions/setup-python@v5.3.0
+        with:
+          python-version: 3.13.1
+
+      - name: Install make
+        run: sudo apt-get update && sudo apt-get install -y make
+
+      - name: Run Tests
+        run: make test
