name: CI

on: [push]

jobs:
 test:
   name: Pytest
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4.2.2

   - name: Set up Python
     uses: actions/setup-python@v5.3.0
     with:
       python-version: 3.13.1

   - name: Install Make
     run: sudo apt-get update && sudo apt-get install -y make

   - name: Test
     run: make test